/** `world.tscn`: the `Ship` instance sits at `position = Vector2(198, 500)`, `scale = Vector2(3, 3)`. */
export const SHIP_POSITION = { x: 198, y: 500 };
export const SHIP_SCALE = 3;

/** `ship.tscn`: `ShipAnimatedSprite2D.position = Vector2(2, 23)` (local to the Ship node). */
export const SHIP_SPRITE_OFFSET = { x: 2, y: 23 };

/**
 * Where each hull's plumes attach, in sprite pixels relative to the hull sprite.
 *
 * Generated by `tools/generate.py` from the nozzle positions the hulls are
 * actually drawn with, so a redesigned engine cannot drift away from its flame.
 * Re-run the generator and paste its output here if a hull changes.
 */
export const THRUSTER_OFFSETS: Record<
  number,
  { left: { x: number; y: number }; right: { x: number; y: number } }
> = {
  0: { left: { x: -6, y: 29 }, right: { x: 5, y: 29 } },
  1: { left: { x: -6, y: 29 }, right: { x: 5, y: 29 } }, // Ranger
  2: { left: { x: -11, y: 28 }, right: { x: 10, y: 28 } }, // Lander
  3: { left: { x: -8, y: 26 }, right: { x: 7, y: 26 } }, // Endurance
  4: { left: { x: -11, y: 26 }, right: { x: 10, y: 26 } }, // TARS
  5: { left: { x: -11, y: 23 }, right: { x: 10, y: 23 } }, // CASE
  6: { left: { x: -3, y: 26 }, right: { x: 2, y: 26 } }, // Lazarus Pod
};

/** Hull number -> the craft it is modelled on, for docs and the asset pipeline. */
export const HULL_NAMES: Record<number, string> = {
  1: 'Ranger',
  2: 'Lander',
  3: 'Endurance',
  4: 'TARS',
  5: 'CASE',
  6: 'Lazarus Pod',
};

/** `SpriteFrames_le0bn`: two 48x48 regions of `turbo_blue.png`, `speed = 10.0`, looping. */
export const THRUSTER_FRAME_COUNT = 2;
export const THRUSTER_FPS = 10;

/** Ship-local coordinates -> the 393x852 design surface. */
export function toDesignSpace(local: { x: number; y: number }) {
  return {
    x: SHIP_POSITION.x + SHIP_SCALE * local.x,
    y: SHIP_POSITION.y + SHIP_SCALE * local.y,
  };
}

/**
 * `ship.gd -> set_thruster_position()`:
 *
 *   thruster.position = ship_animated_sprite_2d.position + offsets[side]
 *
 * `ship.gd` falls back to the entry for hull 0 when a hull has no offsets.
 */
export function getThrusterLocalPositions(shipHull: number) {
  const offsets = THRUSTER_OFFSETS[shipHull] ?? THRUSTER_OFFSETS[0];
  return {
    left: {
      x: SHIP_SPRITE_OFFSET.x + offsets.left.x,
      y: SHIP_SPRITE_OFFSET.y + offsets.left.y,
    },
    right: {
      x: SHIP_SPRITE_OFFSET.x + offsets.right.x,
      y: SHIP_SPRITE_OFFSET.y + offsets.right.y,
    },
  };
}

/** `destroyed_component.gd`: the explosion spawns at `actor.global_position + Vector2(0, 100)`. */
export function getShipDestroyPosition() {
  return { x: SHIP_POSITION.x, y: SHIP_POSITION.y + 100 };
}
